// Query ALL remediator messages at 12:39 on Jan 14
let qFrom = datetime("2026-01-14T12:39:40Z");
let qTo = datetime("2026-01-14T12:39:50Z");
let qCCP = "67e347c35b89890001621aeb";
CPRemediatorLogs
| where PreciseTimeStamp between (qFrom .. qTo)
| where namespace == qCCP
| extend logPreciseTime = todatetime(logPreciseTime)
| extend alert = tostring(alert)
| extend msg = tostring(msg)
| project logPreciseTime, alert, msg
| distinct logPreciseTime, alert, msg
| order by logPreciseTime asc
