// Query the first alerts on Jan 14 around the time nodes went NotReady
let qFrom = datetime("2026-01-14T12:20:00Z");
let qTo = datetime("2026-01-14T12:40:00Z");
let qCCP = "67e347c35b89890001621aeb";
CPRemediatorLogs
| where PreciseTimeStamp between (qFrom .. qTo)
| where namespace == qCCP
| extend logPreciseTime = todatetime(logPreciseTime)
| extend alert = tostring(alert)
| extend msg = tostring(msg)
| where msg !has "config reloaded"
| project logPreciseTime, alert, msg
| distinct logPreciseTime, alert, msg
| order by logPreciseTime asc
